# Generated by Django 4.2.1 on 2024-09-10 00:43

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Модель:"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        default=None,
                        editable=False,
                        populate_from="num",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название:")),
                ("price", models.IntegerField(verbose_name="Цена:")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/",
                        verbose_name="Фото:",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="...",
                        max_length=510,
                        verbose_name="Заметка:",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания товара"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="sport_event.card",
                    ),
                ),
            ],
        ),
    ]
