# Generated by Django 4.2.16 on 2024-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event', '0002_achievement_athlete_coach_competition_result_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата основания'),
        ),
    ]
